name: "Debug"
on:
  repository_dispatch:
      types:
        - debug
jobs:
  debug:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - run: |
        nix-channel --update
        echo "FIXME workaround channel permission error"
    - run: nix-shell
    - uses: mxschmitt/action-tmate@v2
